#ifndef CERT_PEM_H
#define CERT_PEM_H

const char *cert_pem = \
"-----BEGIN CERTIFICATE-----\n" \
"MIIDkTCCAxegAwIBAgISA6zPC6ya1h0O+ymwij3zERDvMAoGCCqGSM49BAMDMDIx\n" \
"CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF\n" \
"NTAeFw0yNTAyMDIxNzI3NDBaFw0yNTA1MDMxNzI3MzlaMBsxGTAXBgNVBAMMECou\n" \
"bmdyb2stZnJlZS5hcHAwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQJOnqig+aa\n" \
"JGny0C7oSG9RzTtjOM19BnNI0GBseoTQTK8xH9QuEbee0nGUMpVVAleT9YJVwo5F\n" \
"8vgBcDnKqpH/o4ICIjCCAh4wDgYDVR0PAQH/BAQDAgeAMB0GA1UdJQQWMBQGCCsG\n" \
"AQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBRqLXNaTVsi\n" \
"A9T84DhJrN4vzbP6rjAfBgNVHSMEGDAWgBSfK1/PPCFPnQS37SssxMZwi9LXDTBV\n" \
"BggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9lNS5vLmxlbmNyLm9y\n" \
"ZzAiBggrBgEFBQcwAoYWaHR0cDovL2U1LmkubGVuY3Iub3JnLzArBgNVHREEJDAi\n" \
"ghAqLm5ncm9rLWZyZWUuYXBwgg5uZ3Jvay1mcmVlLmFwcDATBgNVHSAEDDAKMAgG\n" \
"BmeBDAECATCCAQQGCisGAQQB1nkCBAIEgfUEgfIA8AB2AE51oydcmhDDOFts1N8/\n" \
"Uusd8OCOG41pwLH6ZLFimjnfAAABlMfpuIEAAAQDAEcwRQIhAKo8hJG2XFB2RmSf\n" \
"Do81b8wMVrBUFlxDm88m8h7ih58zAiBuPPnoOsDjxz/Gx0uASEyKB6NICRe02sN/\n" \
"Dr/mq16GiwB2ABNK3xq1mEIJeAxv70x6kaQWtyNJzlhXat+u2qfCq+AiAAABlMfp\n" \
"uS8AAAQDAEcwRQIgZ1yzNbCGAFF2/snEV5t5w1WOaff+R1ScJtajyK5xJRsCIQDv\n" \
"ueiUokWWRxDhnvXu0v3cek2IFvtxbPFnfn1HMQL0vzAKBggqhkjOPQQDAwNoADBl\n" \
"AjEAndoZPWX5hKx5WVaPlAMq64uvB9mh8HOJSvmqICEWFG8/ywJbNfwJNGL0UPPF\n" \
"vfhkAjAXm6M7LPdvCE4CuanMYs0OOWUCKkDiGxIRW8d6bc6NW+drMNcJZURj+TKQ\n" \
"cwWc1is=\n" \
"-----END CERTIFICATE-----\n";

#endif